esphome:
  name: roomsens-one-office

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "demo123!"
  on_client_connected:
    then:
      # Home Assistant connected -> GREEN
      - light.turn_on:
          id: rgb
          brightness: 50%
          red: 0%
          green: 100%
          blue: 0%

  on_client_disconnected:
    then:
      # HA disconnected: fall back to Wi-Fi state
      - if:
          condition:
            wifi.connected:
          then:
            - light.turn_on: # Wi-Fi connected, HA may not be connected yet -> YELLOW
                id: rgb
                brightness: 50%
                red: 100%
                green: 70%
                blue: 0%
          else: # Wi-Fi disconnected -> RED
            - light.turn_on:
                id: rgb
                brightness: 50%
                red: 100%
                green: 0%
                blue: 0%
ota:
  - platform: esphome
    password: "demo123!"

wifi:
  ssid: "MDv2"
  password: "Seinodernichtsein"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "lxroom_buero"
    password: "hhY9PttkuZbH"
  on_connect:
    then:
      # Wi-Fi connected, HA may not be connected yet -> YELLOW
      - light.turn_on:
          id: rgb
          brightness: 50%
          red: 100%
          green: 70%
          blue: 0%

  on_disconnect:
    then:
      # No Wi-Fi -> RED
      - light.turn_on:
          id: rgb
          brightness: 50%
          red: 100%
          green: 0%
          blue: 0%

captive_portal:

# CHANGE THIS PIN to the onboard RGB LED data pin
substitutions:
  rgb_pin: GPIO8   # <-- common on many ESP32 boards; adjust for your board

light:
  - platform: esp32_rmt_led_strip
    id: rgb
    name: "Onboard RGB LED"
    pin: ${rgb_pin}
    num_leds: 1
    rgb_order: GRB        # WS2812 is usually GRB
    chipset: ws2812
    restore_mode: ALWAYS_OFF


# I2C bus (CHANGE PINS!)
i2c:
  sda: GPIO21
  scl: GPIO20
  scan: true
  frequency: 100kHz

sensor:
  - platform: aht10
    temperature:
      name: "AHT20 Temperature"
    humidity:
      name: "AHT20 Humidity"
    address: 0x38
    update_interval: 30s
  - platform: bmp280_i2c
    id: bmp280_sensor
    temperature:
      name: "BMP280 Temperature"
    pressure:
      id: bmp280_pressure
      name: "BMP280 Pressure"
    address: 0x77
    update_interval: 30s
  - platform: template
    name: "BMP280 Altitude"
    unit_of_measurement: "m"
    icon: "mdi:image-filter-hdr"
    update_interval: 30s
    lambda: |-
      return 44330.0 * (1.0 - pow(id(bmp280_pressure)->state / 1013.25, 0.1903));
