sensor:
  - platform: aht10
    temperature:
      name: "${friendly_name} AHT20 Temperature"
    humidity:
      name: "${friendly_name} AHT20 Humidity"
    address: 0x38
    update_interval: 30s
  - platform: bmp280_i2c
    id: bmp280_sensor
    temperature:
      name: "${friendly_name} BMP280 Temperature"
    pressure:
      id: bmp280_pressure
      name: "${friendly_name} BMP280 Pressure"
    address: 0x77
    update_interval: 30s
  - platform: template
    name: "${friendly_name} BMP280 Altitude"
    unit_of_measurement: "m"
    icon: "mdi:image-filter-hdr"
    update_interval: 30s
    lambda: |-
      return 44330.0 * (1.0 - pow(id(bmp280_pressure)->state / 1013.25, 0.1903));